Log:
    Level: "Info"
#    LogDir: ""
#    LogFile: "log.log"
    RaftLevel: "Info"
    DockerLevel: "Error"
Rpc:
    Port: 9000
    Timeout: 50
    UseTLS: false
    TLSCaPath: "./crypt/ca.pem"
    TLSKeyPath: "./crypt/key.pem"
    TLSCertPath: "./crypt/cert.pem"
    TLSServerName: "test.example.com"
Node:
    NodeCertPath: "./cert/nodeCert.pem"
#    NodeKeyPath: "./cert/nodeKey.pem"
#    RootCertPath: "./cert/root.pem"
#    Admin: "5U8r2mWJF1STKHAFEPMn4WiQgXrYa4XuhHwrm2x1ax7xSjBzPbjT2NuJbVcnXSt2ohkvqJ7Y5jUmXxKMoHBLVg34"
StorePath:
    Path: "peer.db"
Crypt:
    KeyTyp: "sm2"
    HashTyp: "sm3"
#    KeyPath: "./crypt/key.pem"
Docker:
    Ip: "0.0.0.0"
    Port: "7051"
    Endpoint: unix:///var/run/docker.sock
    BaseImageVersion: "1.0.1"
    Enable: true
Raft:
    HeartBeat: 500
    VoteTimeout: 5000
BlockChain:
    BlockSize: 1024000
    PackTime: 3000
P2P:
    Cycle: 5000
